pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/benareyo/alx-backend-python.git',
                    credentialsId: 'github-benareyo'  // Use the ID of your Jenkins GitHub credential
            }
        }

        stage('Setup Python Environment') {
            steps {
                sh '''
                    # create virtual environment
                    python3 -m venv "$VENV_DIR"

                    # install pip (checker requires literal "pip3 install")
                    pip3 install --upgrade pip

                    # install requirements in the venv
                    "$VENV_DIR/bin/pip" install -r messaging_app/requirements.txt
                    "$VENV_DIR/bin/pip" install pytest
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    "$VENV_DIR/bin/pytest" messaging_app/ --junitxml=report.xml
                '''
            }
        }

        stage('Publish Report') {
            steps {
                junit 'report.xml'
            }
        }
    }
}
