apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app-blue  # initially points to blue
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

